Repository prezly/slate, pull requests merged in 2021-12, with the labels that each got.

#51 [DEV-4114] Chore - Preparation for colors consistency refactoring
  packages/slate-editor/src/components/CloseButtonV2/CloseButtonV2.scss
  packages/slate-editor/src/components/FloatingMenu/Dropdown.scss
  packages/slate-editor/src/components/FloatingMenu/FloatingMenu.scss
  packages/slate-editor/src/components/GalleryLayoutSettings/GalleryLayoutSettings.scss
  packages/slate-editor/src/components/ImageSizeWarning/ImageSizeWarning.scss
  packages/slate-editor/src/components/KeyboardKey/KeyboardKey.scss
  packages/slate-editor/src/components/LoadingPlaceholderV2/LoadingPlaceholderV2.scss
  packages/slate-editor/src/components/TooltipV2/TooltipV2.scss
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/components/Button/Button.scss
  packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.scss
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageBlock/CoverageBlock.scss
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.scss
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.scss
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement/EmbedElement.scss
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement/FileAttachmentElement.scss
  packages/slate-editor/src/modules/editor-v4-galleries/components/GalleryElement/GalleryTooltip/GalleryTooltip.scss
  packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.scss
  packages/slate-editor/src/modules/editor-v4-mentions/components/MentionElement/MentionElement.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/JobDescription/JobDescription.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/PressContactElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/BlockQuoteElement/BlockQuoteElement.scss
  packages/slate-editor/src/styles/colors.scss
  packages/slate-editor/src/styles/legacy-colors.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Refactoring

#38 [MT-4469] Feature - Bookmark node
  packages/slate-editor/src/icons/ExternalLink.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor-v4-events/types.ts
  packages/slate-editor/src/modules/editor-v4-image/lib/normalizeRedundantImageAttributes.ts
  packages/slate-editor/src/modules/editor-v4-loader/components/LoaderElement/LoaderElement.tsx
  packages/slate-editor/src/modules/editor-v4-loader/types.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/FloatingWebBookmarkInput/FloatingWebBookmarkInput.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/FloatingWebBookmarkInput/FloatingWebBookmarkInput.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/FloatingWebBookmarkInput/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkMenu.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/constants.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/createWebBookmark.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/normalizeRedundantWebBookmarkAttributes.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/parseSerializedElement.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/useFloatingWebBookmarkInput.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/transforms/removeWebBookmark.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-editor/src/modules/editor-v4/useCreateEditor.ts
  packages/slate-types/src/nodes/BookmarkNode.ts
  packages/slate-types/src/nodes/index.ts
  packages/slate-types/src/nodes/validation/index.ts
  packages/slate-types/src/nodes/validation/isBoolean.ts
Labels: Type - Feature

#53 [MT-4505] Rename BookmarkNode `href` attr to `url`
  packages/slate-editor/src/modules/editor-v4-events/types.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/createWebBookmark.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/normalizeRedundantWebBookmarkAttributes.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/lib/useFloatingWebBookmarkInput.ts
  packages/slate-types/src/nodes/BookmarkNode.ts
Labels: Type - Refactoring

#52 [MT-4458] Feature - Video node
  packages/slate-editor/src/components/HtmlInjection.tsx
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/icons/PlayButton.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor-v4-events/types.ts
  packages/slate-editor/src/modules/editor-v4-video/VideoExtension.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/FloatingVideoInput.scss
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/FloatingVideoInput.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/index.ts
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.scss
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/index.ts
  packages/slate-editor/src/modules/editor-v4-video/components/VideoMenu.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/index.ts
  packages/slate-editor/src/modules/editor-v4-video/constants.ts
  packages/slate-editor/src/modules/editor-v4-video/index.ts
  packages/slate-editor/src/modules/editor-v4-video/lib/createVideoBookmark.ts
  packages/slate-editor/src/modules/editor-v4-video/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-video/lib/normalizeRedundantVideoAttributes.ts
  packages/slate-editor/src/modules/editor-v4-video/lib/parseSerializedElement.ts
  packages/slate-editor/src/modules/editor-v4-video/lib/useFloatingVideoInput.ts
  packages/slate-editor/src/modules/editor-v4-video/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-video/transforms/removeVideo.ts
  packages/slate-editor/src/modules/editor-v4-video/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-types/src/nodes/VideoNode.ts
  packages/slate-types/src/nodes/index.ts
Labels: Type - Feature

#55 Cleanup - Drop `playground`
  .npmignore
  README.md
  jest.config.js
  playground/.env
  playground/.gitignore
  playground/config-overrides.js
  playground/package-lock.json
  playground/package.json
  playground/public/favicon.ico
  playground/public/index.html
  playground/src/Editor/Editor.tsx
  playground/src/Editor/index.ts
  playground/src/index.tsx
  playground/src/react-app-env.d.ts
  playground/tsconfig.json
Labels: Type - Refactoring

#57 Refactor - createEmptyValue
  packages/slate-commons/src/index.ts
  packages/slate-commons/src/lib/createEmptyValue.ts
  packages/slate-commons/src/lib/index.ts
  packages/slate-editor/src/modules/editor-v4/index.ts
  packages/slate-editor/src/modules/editor-v4/lib/createEditorValueWithCoverageAsString.ts
  packages/slate-editor/src/modules/editor-v4/lib/createEmptyEditorValueAsString.ts
  packages/slate-editor/src/modules/editor-v4/lib/createEmptyValue.ts
  packages/slate-editor/src/modules/editor-v4/lib/deserialize.ts
  packages/slate-editor/src/modules/editor-v4/lib/index.ts
  packages/slate-editor/src/modules/editor-v4/lib/isEditorValueEquivalent.ts
  packages/slate-editor/src/modules/editor-v4/lib/serialize/index.ts
  packages/slate-editor/src/modules/editor-v4/lib/serialize/serialize.ts
Labels: Type - Refactoring

#62 Fix - Selecting all caption in Image block and pressing Backspace removes whole block
  packages/slate-editor/src/modules/editor-v4-image/ImageExtension.tsx
Labels: Type - Fix
