Repository prezly/slate, pull requests merged in 2022-03, with the labels that each got.

#120 [DEV-4692] Correctly set max-height of a mentions dropdown
  packages/slate-editor/src/modules/editor-v4-mentions/components/MentionsDropdown/MentionsDropdown.scss
Labels: Type - Fix

#121 [MT-4621] File attachment settings menu
  .prettierignore
  packages/slate-editor/src/modules/editor-v4-file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/FileAttachment.module.scss
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/FileAttachment.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/Subtitle.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/Title.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/index.ts
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement/FileAttachmentElement.scss
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement/FileAttachmentElement.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement/index.ts
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentMenu.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/index.ts
  packages/slate-editor/src/modules/editor-v4-file-attachment/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/lib/file-attachment/handleEditAttachment.ts
Labels: Type - Feature

#108 [MT-4636] Cleanup - Old [+] menu UI
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ClassicDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ClassicDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/menuOptions.tsx
Labels: Type - Refactoring

#122 [DEV-5076] Sennheiser - StoryEmbedNode - Multi-license Story picker
  packages/slate-editor/src/modules/editor-v4-events/types.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.tsx
  packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/useFloatingStoryEmbedInput.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
Labels: Type - Feature, Priority - High

#124 [MT-4616] Refactor - Selection mark to runtime decorations
  packages/slate-commons/src/EditableWithExtensions.tsx
  packages/slate-commons/src/lib/combineDecorate.ts
  packages/slate-commons/src/lib/createExtensionsDecorators.ts
  packages/slate-commons/src/lib/decorateExtensions.ts
  packages/slate-commons/src/lib/index.ts
  packages/slate-commons/src/types/DecorateFactory.ts
  packages/slate-commons/src/types/Extension.ts
  packages/slate-commons/src/types/index.ts
  packages/slate-editor/src/modules/editor-v4-decorate-selection/DecorateSelectionExtension.tsx
  packages/slate-editor/src/modules/editor-v4-decorate-selection/components/SelectionHighlight.module.scss
  packages/slate-editor/src/modules/editor-v4-decorate-selection/components/SelectionHighlight.tsx
  packages/slate-editor/src/modules/editor-v4-decorate-selection/components/index.ts
  packages/slate-editor/src/modules/editor-v4-decorate-selection/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/RichFormattingMenu.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Text.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Text/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-editor/src/modules/editor-v4/useCreateEditor.ts
Labels: Type - Refactoring

#135 Refactor - Deprecate ImageNode `width_factor` property
  packages/slate-editor/src/modules/editor-v4-image/components/ImageElement/ImageElement.tsx
  packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.tsx
  packages/slate-editor/src/modules/editor-v4-image/jsx.ts
  packages/slate-editor/src/modules/editor-v4-image/lib/createImage.ts
  packages/slate-editor/src/modules/editor-v4-image/lib/normalizeRedundantImageAttributes.ts
  packages/slate-editor/src/modules/editor-v4-image/lib/parseSerializedElement.ts
  packages/slate-editor/src/modules/editor-v4-image/transforms/removeImage.test.tsx
  packages/slate-editor/src/modules/editor-v4-image/withImages.test.tsx
  packages/slate-editor/src/modules/editor-v4/json.ts
  packages/slate-editor/src/modules/editor-v4/lib/images/createHandleEditImage.ts
  packages/slate-types/src/nodes/ImageNode.ts
Labels: Type - Refactoring
