Repository prezly/slate, pull requests merged in 2022-04, with the labels that each got.

#139 [MT-4881] fixed placeholder issue with mentions
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/commands/isEmptyParagraphElement.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/shouldShowMenuButton.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.stories.tsx
Labels: Type - Fix

#86 [MT-4590] Feature - [+] button in heading elements
  packages/slate-editor/src/components/KeyboardKey/KeyboardKey.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.module.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenuExtension.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/shouldShowMenuButton.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Headings/HeadingElement.scss
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/styles/shared.scss
  packages/slate-types/src/nodes/HeadingNode.ts
Labels: Type - Feature

#150 Upgrade - Slate
  .eslintrc.cjs
  README.md
  package-lock.json
  package.json
  packages/slate-commons/package.json
  packages/slate-commons/src/jsx.ts
  packages/slate-commons/tsconfig.build.json
  packages/slate-commons/tsconfig.json
  packages/slate-editor/package.json
  packages/slate-editor/src/modules/editor-v4-coverage/jsx.ts
  packages/slate-editor/src/modules/editor-v4-divider/jsx.ts
  packages/slate-editor/src/modules/editor-v4-file-attachment/jsx.ts
  packages/slate-editor/src/modules/editor-v4-image/jsx.ts
  packages/slate-editor/src/modules/editor-v4-loader/jsx.ts
  packages/slate-editor/src/modules/editor-v4-mentions/jsx.ts
  packages/slate-editor/src/modules/editor-v4-mentions/lib/insertMention.ts
  packages/slate-editor/src/modules/editor-v4-paragraphs/jsx.ts
  packages/slate-editor/src/modules/editor-v4-placeholder-mentions/jsx.ts
  packages/slate-editor/src/modules/editor-v4-user-mentions/jsx.ts
  packages/slate-editor/src/modules/editor-v4/README.md
  packages/slate-editor/src/modules/editor-v4/jsx.ts
  packages/slate-editor/src/modules/editor-v4/plugins/withDeserializeHtml/createDeserialize/createDeserialize.ts
  packages/slate-editor/src/modules/editor-v4/plugins/withDeserializeHtml/createDeserialize/deserializeHtmlToElement.ts
  packages/slate-editor/src/modules/editor-v4/plugins/withDeserializeHtml/createDeserialize/deserializeHtmlToMarks.ts
  packages/slate-editor/tsconfig.build.json
  packages/slate-editor/tsconfig.json
  packages/slate-hyperscript/.npmrc
  packages/slate-hyperscript/README.md
  packages/slate-hyperscript/gulpfile.js
  packages/slate-hyperscript/package.json
  packages/slate-hyperscript/src/createHyperscript.ts
  packages/slate-hyperscript/src/index.ts
  packages/slate-hyperscript/src/slate-hyperscript/creators.ts
  packages/slate-hyperscript/src/slate-hyperscript/hyperscript.ts
  packages/slate-hyperscript/src/slate-hyperscript/index.ts
  packages/slate-hyperscript/src/slate-hyperscript/tokens.ts
  packages/slate-hyperscript/tsconfig.build.json
  packages/slate-hyperscript/tsconfig.json
  packages/slate-lists/package.json
  packages/slate-lists/tsconfig.build.json
  packages/slate-lists/tsconfig.json
  packages/slate-types/package.json
  tsconfig.json
Labels: Type - Refactoring

#152 [MT-4872] Feature - New ImageNode model features
  packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Size.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/isMenuHotkey.ts
  packages/slate-editor/src/modules/editor-v4-image/components/ImageElement.tsx
  packages/slate-editor/src/modules/editor-v4-image/lib/createImage.ts
  packages/slate-editor/src/modules/editor-v4-image/lib/normalizeRedundantImageAttributes.ts
  packages/slate-types/src/nodes/ImageNode.ts
Labels: Type - Feature

#155 [MT-4670] Fix - Placeholder should not be visible for white-space-only text blocks
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
Labels: Type - Bug
