Repository prezly/slate, pull requests merged in 2022-02, with the labels that each got.

#87 [MT-4450] Creating a Link does not focus URL input
  packages/slate-editor/src/components/Portals/BasePortalV2.scss
  packages/slate-editor/src/components/Portals/BasePortalV2.tsx
  packages/slate-editor/src/components/Portals/convertClientRect.ts
  packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/RichFormattingMenu.tsx
Labels: Type - Bug

#90 [MT-4661] Scrolling in the dropdown does not work on Mac
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
Labels: Type - Bug

#88 [MT-4535] Show add button for empty block including spaces
  package-lock.json
  packages/slate-commons/src/commands/isCursorInEmptyParagraph.ts
  packages/slate-commons/src/commands/isEmptyParagraphElement.test.tsx
  packages/slate-commons/src/commands/isEmptyParagraphElement.ts
  packages/slate-commons/src/commands/isNodeEmpty.test.tsx
  packages/slate-editor/package-lock.json
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenuExtension.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/shouldShowMenuButton.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/toggleBlock.ts
Labels: Type - Bug

#96 [MT-4669] Feature - Consistent [+] dropdown scrollbars
  .gitignore
  package-lock.json
  packages/slate-editor/.gitignore
  packages/slate-editor/package.json
  packages/slate-editor/src/components/FancyScrollbars.module.scss
  packages/slate-editor/src/components/FancyScrollbars.tsx
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.tsx
  packages/slate-editor/src/styles/mixins.scss
Labels: Type - Feature

#99 [MT-4593] Cleanup - Light toolbar UI
  packages/slate-editor/src/components/GalleryLayoutSettings/GalleryLayoutSettings.scss
  packages/slate-editor/src/components/GalleryLayoutSettings/GalleryLayoutSettings.tsx
  packages/slate-editor/src/components/Menu/ButtonGroup.tsx
  packages/slate-editor/src/components/Menu/Dropdown.scss
  packages/slate-editor/src/components/Menu/Menu.scss
  packages/slate-editor/src/components/Menu/Toolbar.tsx
  packages/slate-editor/src/components/Menu/_mixins.scss
  packages/slate-editor/src/icons/Contained.svg
  packages/slate-editor/src/icons/Expanded.svg
  packages/slate-editor/src/icons/FullWidth.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.scss
  packages/slate-editor/src/modules/editor-v4-components/LinkMenu/LinkMenu.tsx
  packages/slate-editor/src/modules/editor-v4-galleries/components/GalleryElement/GalleryTooltip/GalleryTooltip.scss
  packages/slate-editor/src/modules/editor-v4-galleries/components/LayoutControls.tsx
  packages/slate-editor/src/modules/editor-v4-image/components/ImageElement/ImageElement.tsx
  packages/slate-editor/src/modules/editor-v4-image/components/LayoutControls.tsx
  packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.scss
  packages/slate-editor/src/modules/editor-v4-image/components/ResizableContainer/ResizableContainer.tsx
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-editor/src/modules/themes/index.tsx
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Refactoring

#98 [MT-4672] Fix - [+] button menu keyboard navigation
  packages/slate-editor/src/components/FancyScrollbars.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/sortBetaOptionsLast.ts
Labels: Type - Fix

#100 [MT-4667] Escape current link node when space is typed at the right boundary
  packages/slate-editor/src/modules/editor-v4-rich-formatting/createOnKeyDown.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/isCursorAtEndOfLink.ts
Labels: Type - Feature

#102 [MT-4646] Feature - New component toolbox popover container
  .prettierignore
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Menu.tsx
  packages/slate-editor/src/components/EditorBlock/Overlay.tsx
  packages/slate-editor/src/components/EditorBlock/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/lib/hooks/index.ts
  packages/slate-editor/src/lib/hooks/useSlateDom.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.module.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/styles/colors.scss
Labels: Type - Feature

#101 [MT-4662] New components menus: Phase 1
  .eslintrc.cjs
  package-lock.json
  packages/slate-editor/.storybook/main.cjs
  packages/slate-editor/.storybook/preview-head.html
  packages/slate-editor/package.json
  packages/slate-editor/src/@types/utils.d.ts
  packages/slate-editor/src/components/Button/Button.module.scss
  packages/slate-editor/src/components/Button/Button.stories.tsx
  packages/slate-editor/src/components/Button/Button.tsx
  packages/slate-editor/src/components/Button/index.ts
  packages/slate-editor/src/components/OptionsGroup/Option.tsx
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.module.scss
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.stories.tsx
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.tsx
  packages/slate-editor/src/components/OptionsGroup/index.ts
  packages/slate-editor/src/components/Stack/HStack.tsx
  packages/slate-editor/src/components/Stack/Stack.module.scss
  packages/slate-editor/src/components/Stack/Stack.stories.tsx
  packages/slate-editor/src/components/Stack/Stack.tsx
  packages/slate-editor/src/components/Stack/VStack.tsx
  packages/slate-editor/src/components/Stack/index.ts
  packages/slate-editor/src/components/Toggle/Toggle.module.scss
  packages/slate-editor/src/components/Toggle/Toggle.stories.tsx
  packages/slate-editor/src/components/Toggle/Toggle.tsx
  packages/slate-editor/src/components/Toggle/index.ts
  packages/slate-editor/src/components/Toolbox/Caption.tsx
  packages/slate-editor/src/components/Toolbox/Footer.tsx
  packages/slate-editor/src/components/Toolbox/Header.tsx
  packages/slate-editor/src/components/Toolbox/Panel.tsx
  packages/slate-editor/src/components/Toolbox/Section.tsx
  packages/slate-editor/src/components/Toolbox/Toolbox.module.scss
  packages/slate-editor/src/components/Toolbox/Toolbox.stories.tsx
  packages/slate-editor/src/components/Toolbox/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/icons/Items-Layout-Horizontal.svg
  packages/slate-editor/src/icons/Items-Layout-Vertical.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/styles/variables.scss
  tsconfig.json
Labels: Type - Feature

#104 [MT-4617] Feature - New focus state colors
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/modules/editor-v4-divider/DividerExtension.tsx
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.module.scss
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.scss
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.tsx
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerMenu.tsx
  packages/slate-editor/src/modules/editor-v4-divider/components/index.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/styles/shared.scss
Labels: Type - Feature

#105 [MT-4673] Fix - Pressing UP key doesnt focus some void elements
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/modules/editor-v4-divider/components/DividerElement.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.module.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/styles/shared.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Fix

#103 [MT-4618] Feature - Web Bookmark menu
  packages/slate-editor/src/components/Button/Button.module.scss
  packages/slate-editor/src/components/Button/Button.stories.tsx
  packages/slate-editor/src/components/Button/Button.tsx
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Menu.tsx
  packages/slate-editor/src/components/EditorBlock/Overlay.tsx
  packages/slate-editor/src/components/Toggle/Toggle.stories.tsx
  packages/slate-editor/src/components/Toggle/Toggle.tsx
  packages/slate-editor/src/components/Toolbox/Header.tsx
  packages/slate-editor/src/components/Toolbox/Panel.tsx
  packages/slate-editor/src/components/Toolbox/Toolbox.module.scss
  packages/slate-editor/src/components/Toolbox/Toolbox.stories.tsx
  packages/slate-editor/src/icons/Items-Layout-Horizontal.svg
  packages/slate-editor/src/icons/Items-Layout-Vertical.svg
  packages/slate-editor/src/modules/editor-v4-web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkMenu.module.scss
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkMenu.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkMenu.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/transforms/updateWebBookmark.ts
  packages/slate-editor/src/modules/editor-v4-web-bookmark/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
Labels: Type - Feature

#107 [MT-4552] Feature - HTML blocks support
  packages/slate-editor/src/modules/editor-v4-html/HtmlExtension.tsx
  packages/slate-editor/src/modules/editor-v4-html/components/HtmlElement.tsx
  packages/slate-editor/src/modules/editor-v4-html/components/index.ts
  packages/slate-editor/src/modules/editor-v4-html/constants.ts
  packages/slate-editor/src/modules/editor-v4-html/index.ts
  packages/slate-editor/src/modules/editor-v4-html/lib/createHtmlBlock.ts
  packages/slate-editor/src/modules/editor-v4-html/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-html/lib/normalizeRedundantHtmlBlockAttributes.ts
  packages/slate-editor/src/modules/editor-v4-html/lib/parseSerializedElement.ts
  packages/slate-editor/src/modules/editor-v4-html/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-html/transforms/removeHtmlBlock.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-types/src/nodes/HtmlNode.ts
  packages/slate-types/src/nodes/index.ts
Labels: Type - Feature

#116 Move `Extension.withOverrides` support into `createEditorV4()`
  packages/slate-commons/src/types/index.ts
  packages/slate-editor/src/modules/editor-v4/createEditorV4.ts
  packages/slate-editor/src/modules/editor-v4/useCreateEditor.ts
Labels: Type - Refactoring

#118 [DEV-4541] Story Embed rich content block
  packages/slate-editor/src/modules/editor-v4-events/types.ts
  packages/slate-editor/src/modules/editor-v4-loader/components/LoaderElement/LoaderElement.tsx
  packages/slate-editor/src/modules/editor-v4-loader/types.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/StoryEmbedExtension.tsx
  packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.scss
  packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.tsx
  packages/slate-editor/src/modules/editor-v4-story-embed/components/FloatingStoryEmbedInput/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/StoryEmbedElement.module.scss
  packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx
  packages/slate-editor/src/modules/editor-v4-story-embed/components/StoryEmbedElement/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/components/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/constants.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/createStoryEmbed.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/normalizeRedundantStoryEmbedAttributes.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/parseSerializedElement.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/lib/useFloatingStoryEmbedInput.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/transforms/removeStoryEmbed.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/transforms/updateStoryEmbed.ts
  packages/slate-editor/src/modules/editor-v4-story-embed/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/menuOptions.tsx
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-types/src/nodes/StoryEmbedNode.ts
  packages/slate-types/src/nodes/index.ts
Labels: Type - Feature
