Repository prezly/slate, pull requests merged in 2022-05, with the labels that each got.

#158 [MT-4939] Fixed caption doesn't break on full-width image
  packages/slate-editor/src/modules/editor-v4-image/components/ImageElement.module.scss
Labels: Type - Bug, Type - Fix

#164 [DEV-5520] Refactor - Video element UI
  packages/slate-editor/src/modules/editor-v4-video/VideoExtension.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput.scss
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/index.ts
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement.module.scss
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.scss
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/index.ts
  packages/slate-editor/src/modules/editor-v4-video/components/VideoMenu.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/index.ts
  packages/slate-editor/src/modules/editor-v4-video/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
Labels: Type - Refactoring

#165 [DEV-5520] Refactor - Embed element
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/HtmlInjection.tsx
  packages/slate-editor/src/modules/editor-v4-embed/EmbedExtension.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement.module.scss
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement/EmbedElement.scss
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement/EmbedElement.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement/index.ts
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedMenu.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/FloatingEmbedInput.scss
  packages/slate-editor/src/modules/editor-v4-embed/components/FloatingEmbedInput.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/FloatingEmbedInput/index.ts
  packages/slate-editor/src/modules/editor-v4-embed/components/index.ts
  packages/slate-editor/src/modules/editor-v4-embed/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-embed/lib/injectOembedMarkup.ts
  packages/slate-editor/src/modules/editor-v4-embed/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-editor/src/styles/shared.scss
Labels: Type - Refactoring

#166 [DEV-5520] Refactor - Coverage element
  packages/slate-editor/src/modules/editor-v4-coverage/CoverageExtension.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.module.scss
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.scss
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageMenu.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/components/index.ts
  packages/slate-editor/src/modules/editor-v4-coverage/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
Labels: Type - Refactoring

#167 [DEV-5520] Refactor - PressContact element
  packages/slate-editor/src/modules/editor-v4-press-contacts/PressContactsExtension.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/FloatingPressContactsMenu.module.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/FloatingPressContactsMenu.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/FloatingPressContactsMenu/index.ts
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/JobDescription/JobDescription.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/JobDescription/JobDescription.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/JobDescription/index.ts
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement.module.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/PressContactElement.scss
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/PressContactElement.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/SocialField.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/SocialFields.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement/index.ts
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactMenu.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/index.ts
  packages/slate-editor/src/modules/editor-v4-press-contacts/types.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
Labels: Type - Refactoring

#168 Fix - Blocks borders style
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/modules/editor-v4-components/BookmarkCard/BookmarkCard.module.scss
  packages/slate-editor/src/modules/editor-v4-components/BookmarkCard/BookmarkCard.stories.tsx
  packages/slate-editor/src/modules/editor-v4-components/BookmarkCard/Container.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/EmbedElement.tsx
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachment/FileAttachment.module.scss
  packages/slate-editor/src/modules/editor-v4-file-attachment/components/FileAttachmentElement.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.scss
  packages/slate-editor/src/modules/editor-v4-galleries/components/Gallery/GalleryTile.module.scss
  packages/slate-editor/src/modules/editor-v4-image/components/ImageElement.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/PressContactElement.tsx
  packages/slate-editor/src/modules/editor-v4-story-bookmark/components/StoryBookmarkElement/StoryBookmarkBlock.tsx
  packages/slate-editor/src/modules/editor-v4-story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.tsx
  packages/slate-editor/src/styles/shared.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Fix

#169 Feature - Coverage block nice placeholder for error state
  packages/slate-editor/src/components/ElementPlaceholder/ElementPlaceholder.module.scss
  packages/slate-editor/src/components/ElementPlaceholder/ElementPlaceholder.tsx
  packages/slate-editor/src/components/ElementPlaceholder/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/lib/removeCoverage.ts
  packages/slate-editor/src/modules/editor-v4-story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx
  packages/slate-editor/src/modules/editor-v4-story-bookmark/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-story-bookmark/transforms/updateStoryBookmark.ts
Labels: Type - Feature

#170 Fix CoverageNode model mismatch between frontend and backend
  packages/slate-editor/src/modules/editor-v4-coverage/lib/createCoverage.ts
  packages/slate-editor/src/modules/editor-v4-coverage/lib/normalizeRedundantCoverageAttributes.ts
  packages/slate-editor/src/modules/editor-v4-coverage/lib/parseSerializedElement.ts
  packages/slate-types/src/nodes/CoverageNode.ts
Labels: Type - Fix

#157 [MT-4930] Fix - Visible caret in non-editable elements in Safari
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
Labels: Type - Bug, Type - Fix

#171 [MT-4960] Fix - Menu positioning
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Menu.tsx
Labels: Type - Fix

#172 [MT-4965] Fix - Image menu overlapping with caption
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Overlay.tsx
Labels: Type - Fix

#179 Support - React 18
  .github/workflows/build.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  packages/slate-commons/package.json
  packages/slate-editor/package.json
  packages/slate-editor/src/components/KeyboardKey/KeyboardKey.tsx
  packages/slate-editor/src/components/LoadingPlaceholderV2/Placeholder.tsx
  packages/slate-editor/src/components/Menu/ButtonGroup.tsx
  packages/slate-editor/src/components/Menu/FloatingMenu.tsx
  packages/slate-editor/src/components/Menu/Toolbar.tsx
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/Container.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/isComponent.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/MenuOption.tsx
  packages/slate-lists/package.json
  packages/slate-lists/src/jsx.ts
Labels: Type - Feature

#182 Refactor - Rich Formatting dropdown
  .eslintrc.cjs
  packages/slate-editor/src/components/Menu/Button.tsx
  packages/slate-editor/src/components/Menu/ButtonGroup.tsx
  packages/slate-editor/src/components/Menu/Dropdown.module.scss
  packages/slate-editor/src/components/Menu/Dropdown.tsx
  packages/slate-editor/src/components/Menu/FloatingMenu.tsx
  packages/slate-editor/src/components/Menu/Icon.tsx
  packages/slate-editor/src/components/Menu/Link.tsx
  packages/slate-editor/src/components/Menu/Menu.module.scss
  packages/slate-editor/src/components/Menu/SpaLink.tsx
  packages/slate-editor/src/components/Menu/Toolbar.tsx
  packages/slate-editor/src/components/Menu/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/BlockDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/FormattingDropdown.module.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/FormattingDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/MenuOption.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting-menu/components/Toolbar.tsx
Labels: Type - Refactoring

#183 [MT-4981] Fix File Attachment double border
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment/FileAttachment.module.scss
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment/FileAttachment.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment/Subtitle.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment/Title.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachmentElement.tsx
Labels: Type - Fix

#184 Refactor - FileAttachment element
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment.module.scss
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment.tsx
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachment/index.ts
  packages/slate-editor/src/extensions/file-attachment/components/FileAttachmentElement.tsx
  packages/slate-editor/src/extensions/file-attachment/components/index.ts
  packages/slate-editor/src/extensions/file-attachment/index.ts
  packages/slate-editor/src/extensions/file-attachment/lib/index.ts
  packages/slate-editor/src/extensions/file-attachment/lib/isUsingCustomTitle.ts
  packages/slate-editor/src/extensions/file-attachment/types.ts
  packages/slate-editor/src/modules/editor/Editor.stories.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/test-utils.ts
  packages/slate-editor/src/modules/editor/types/index.ts
Labels: Type - Refactoring

#186 [MT-4930] Fix - Caret not visible in block menu inputs
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
Labels: Type - Fix

#190 [MT-4985] Make attachment menu label discoverable by "File" keyword
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#192 Fix - Gallery layout calculation
  packages/slate-editor/src/extensions/galleries/components/Gallery/Gallery.module.scss
  packages/slate-editor/src/extensions/galleries/components/Gallery/Gallery.tsx
  packages/slate-editor/src/extensions/galleries/components/Gallery/GalleryTile.tsx
  packages/slate-editor/src/extensions/galleries/components/Gallery/lib/calculateLayout.ts
Labels: Type - Fix

#191 [MT-4988] Fix - Unable to add link to text in story
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/Menu.tsx
  packages/slate-editor/src/extensions/image/components/ImageElement.tsx
  packages/slate-editor/src/extensions/image/components/ImageMenu.tsx
  packages/slate-editor/src/extensions/image/transforms/removeImage.ts
  packages/slate-editor/src/extensions/image/transforms/updateImage.ts
  packages/slate-editor/src/extensions/web-bookmark/components/FloatingWebBookmarkInput.tsx
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/lib/index.ts
  packages/slate-editor/src/lib/urls.ts
  packages/slate-editor/src/modules/components/LinkMenu/LinkMenu.module.scss
  packages/slate-editor/src/modules/components/LinkMenu/LinkMenu.tsx
  packages/slate-editor/src/modules/components/LinkMenu/constants.ts
  packages/slate-editor/src/modules/components/LinkMenu/index.ts
  packages/slate-editor/src/modules/components/index.ts
  packages/slate-editor/src/modules/rich-formatting-menu/LinkMenu.tsx
Labels: Type - Fix, Type - Refactoring

#197 Refactor - Extensions inline/void checks
  packages/slate-commons/src/plugins/withInlineVoid.ts
  packages/slate-commons/src/plugins/withNormalization.ts
  packages/slate-commons/src/types/Extension.ts
  packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx
  packages/slate-editor/src/extensions/divider/DividerExtension.tsx
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx
  packages/slate-editor/src/extensions/html/HtmlExtension.tsx
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx
  packages/slate-editor/src/extensions/loader/LoaderExtension.tsx
  packages/slate-editor/src/extensions/mentions/MentionsExtension.ts
  packages/slate-editor/src/extensions/mentions/test-utils.tsx
  packages/slate-editor/src/extensions/paragraphs/ParagraphsExtension.tsx
  packages/slate-editor/src/extensions/placeholder-mentions/PlaceholderMentionsExtension.tsx
  packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx
  packages/slate-editor/src/extensions/rich-formatting/RichFormattingExtension.tsx
  packages/slate-editor/src/extensions/story-bookmark/StoryBookmarkExtension.tsx
  packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx
  packages/slate-editor/src/extensions/user-mentions/UserMentionsExtension.tsx
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
Labels: Type - Refactoring

#196 [MT-4991] Fix - iframely embed selection
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Fix

#195 [MT-4990] Fix full-width block layout & selection styling
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/styles/mixins.scss
Labels: Type - Fix

#199 [MT-4984] Fix - Fallbacks for a non embeddable links
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.module.scss
  packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.stories.tsx
Labels: Type - Fix

#198 [DEV-5606] Fix - Erase blockquote/heading on backspace in the beginning of document
  packages/slate-editor/src/extensions/rich-formatting/RichFormattingExtension.tsx
  packages/slate-editor/src/extensions/rich-formatting/createOnKeyDownHandler.ts
  packages/slate-editor/src/extensions/rich-formatting/lib/index.ts
  packages/slate-editor/src/extensions/rich-formatting/lib/withResetFormattingOnBreak.ts
  packages/slate-editor/src/extensions/rich-formatting/onKeyDown.ts
  packages/slate-editor/src/modules/editable/EditableWithExtensions.tsx
Labels: Type - Fix
