Repository prezly/slate, pull requests merged in 2022-07, with the labels that each got.

#228 Add cell content formatting
  packages/slate-commons/src/commands/alignment.ts
  packages/slate-editor/src/extensions/tables/components/TableMenu.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableCellElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableRowElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/elements.module.scss
  packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx
  packages/slate-editor/src/modules/rich-formatting-menu/components/Toolbar.tsx
  packages/slate-editor/src/modules/rich-formatting-menu/types.ts
  packages/slate-tables/src/TablesEditor.tsx
  packages/slate-tables/src/core/Matrix/Matrix.ts
  packages/slate-tables/src/core/Matrix/MatrixCell.ts
  packages/slate-tables/src/core/Matrix/MatrixColumn.ts
  packages/slate-tables/src/core/Matrix/MatrixRow.ts
  packages/slate-tables/src/core/Traverse/Traverse.ts
  packages/slate-tables/src/queries/index.ts
  packages/slate-tables/src/queries/isHeaderCell.ts
Labels: Type - Feature

#229 Fix add new row/column
  packages/slate-tables/src/commands/insertColumn.ts
  packages/slate-tables/src/commands/insertRow.ts
Labels: Type - Fix

#231 Apply table nodes normalization rules
  package-lock.json
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/commands/unsetMark.ts
  packages/slate-editor/src/jsx.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEqual.test.ts
  packages/slate-editor/src/modules/nodes-hierarchy/fixers/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/fixers/liftNodeNoSplit.ts
  packages/slate-editor/src/modules/nodes-hierarchy/fixers/liftNodeWithSplit.ts
  packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/allowChildren.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/allowChildren.ts
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/disallowMark.ts
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedInTableCell.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isDescendantOf.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isEmptyTextNode.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isInlineNode.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isTextNode.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/Tables.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/types.ts
  packages/slate-editor/src/modules/nodes-hierarchy/withNodesHierarchy.ts
  packages/slate-tables/src/nodes/TableNode.ts
  packages/slate-tables/src/queries/isHeaderCell.ts
Labels: Type - Feature

#235 [MT-5070] Fix - Cursor works incorrectly in table cell
  package-lock.json
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/ResizableEditorBlock.tsx
  packages/slate-editor/src/extensions/coverage/components/CoverageElement.tsx
  packages/slate-editor/src/extensions/divider/components/DividerElement.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/galleries/components/GalleryElement.tsx
  packages/slate-editor/src/extensions/html/components/HtmlElement.tsx
  packages/slate-editor/src/extensions/image/components/ImageElement.tsx
  packages/slate-editor/src/extensions/loader/components/LoaderElement.tsx
  packages/slate-editor/src/extensions/press-contacts/components/PressContactElement.tsx
  packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx
  packages/slate-editor/src/extensions/story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx
  packages/slate-editor/src/extensions/story-embed/types.ts
  packages/slate-editor/src/extensions/tables/components/elements/TableCellElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableElement.tsx
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
  packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkElement.tsx
  packages/slate-editor/src/lib/hooks/useFunction.ts
Labels: Type - Fix

#240 [MT-5090][MT-5071] Fix - StoryEmbed element
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/extensions/story-embed/components/StoryEmbedElement/StoryEmbedElement.tsx
  packages/slate-editor/src/extensions/story-embed/lib/createStoryEmbed.ts
Labels: Type - Fix

#245 Refactor - Avoid using nodeIdManager
  packages/slate-commons/src/index.ts
  packages/slate-commons/src/lib/index.ts
  packages/slate-commons/src/lib/nodeIdManager.ts
  packages/slate-lists/src/lib/decreaseDepth.ts
  packages/slate-lists/src/lib/increaseDepth.ts
  packages/slate-lists/src/lib/setListType.ts
  packages/slate-lists/src/lib/wrapInList.ts
Labels: Type - Refactoring

#244 [MT-5160][MT-5161] Fix - Lists bugs
  package-lock.json
  packages/slate-commons/src/commands/alignment.ts
  packages/slate-editor/src/extensions/list/withListsFormatting.ts
  packages/slate-lists/src/lib/setListType.test.tsx
  packages/slate-lists/src/lib/setListType.ts
  packages/slate-lists/src/types.ts
  packages/slate-lists/tsconfig.build.json
  packages/slate-lists/tsconfig.json
Labels: Type - Fix

#242 [MT-5052] Keyboard navigation for tables
  package-lock.json
  packages/slate-commons/package.json
  packages/slate-commons/src/commands/findLeafPath.ts
  packages/slate-commons/src/commands/findLeafPoint.ts
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/commands/moveCursorToNextBlock.ts
  packages/slate-commons/src/commands/moveCursorToPreviousBlock.ts
  packages/slate-editor/package.json
  packages/slate-editor/src/extensions/list/ListExtension.tsx
  packages/slate-editor/src/extensions/tables/TablesExtension.tsx
  packages/slate-lists/package.json
  packages/slate-lists/src/ListsEditor.ts
  packages/slate-lists/src/lib/index.ts
  packages/slate-lists/src/lib/isInList.ts
  packages/slate-tables/package.json
  packages/slate-tables/src/TablesEditor.ts
  packages/slate-tables/src/core/Matrix/Matrix.ts
  packages/slate-tables/src/core/Matrix/MatrixCell.ts
  packages/slate-tables/src/core/Matrix/MatrixRow.ts
  packages/slate-tables/src/core/index.ts
  packages/slate-tables/src/core/onKeyDown.ts
  packages/slate-tables/src/index.ts
  packages/slate-types/package.json
Labels: Type - Feature

#222 [MT-5076] Refactor - Move pre-serialization cleanup to Extension
  packages/slate-commons/src/lib/withoutNodes.ts
  packages/slate-commons/src/types/Extension.ts
  packages/slate-commons/src/types/Serialize.ts
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/image/index.ts
  packages/slate-editor/src/extensions/image/serialization/index.ts
  packages/slate-editor/src/extensions/image/serialization/withoutImageCandidates.ts
  packages/slate-editor/src/extensions/loader/LoaderExtension.tsx
  packages/slate-editor/src/extensions/loader/index.ts
  packages/slate-editor/src/extensions/loader/serialization/index.ts
  packages/slate-editor/src/extensions/loader/serialization/withoutLoaders.ts
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/createEditor.ts
  packages/slate-editor/src/modules/editor/index.ts
  packages/slate-editor/src/modules/editor/lib/createEditorValueWithCoverageAsString.ts
  packages/slate-editor/src/modules/editor/lib/createEmptyEditorValueAsString.ts
  packages/slate-editor/src/modules/editor/lib/deserialize.ts
  packages/slate-editor/src/modules/editor/lib/index.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEqual.test.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEqual.ts
  packages/slate-editor/src/modules/editor/lib/serialize.ts
  packages/slate-editor/src/modules/editor/plugins/index.ts
  packages/slate-editor/src/modules/editor/plugins/withSerialization.ts
Labels: Type - Refactoring

#248 [MT-5184] Feature - Insert blocks above/below current block
  packages/slate-editor/src/extensions/insert-block-hotkey/InsertBlockHotkeyExtension.ts
  packages/slate-editor/src/extensions/insert-block-hotkey/index.ts
  packages/slate-editor/src/extensions/insert-block-hotkey/lib.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
Labels: Type - Feature

#250 [MT-5131] Feature - [+] menu "Suggestions" group
  packages/slate-editor/src/components/FancyScrollbars.tsx
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
  packages/slate-editor/src/extensions/floating-add-menu/lib/groupOptions.ts
  packages/slate-editor/src/extensions/floating-add-menu/lib/index.ts
  packages/slate-editor/src/extensions/floating-add-menu/lib/prependSuggestions.ts
  packages/slate-editor/src/extensions/floating-add-menu/types.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#251 [MT-5132] Feature - Allow tracking of [+] menu options clicks
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenuExtension.tsx
  packages/slate-editor/src/extensions/floating-add-menu/lib/useMenuToggle.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Feature

#252 [MT-5126] Change - Placeholder text copy
  packages/slate-editor/src/components/Key.module.scss
  packages/slate-editor/src/components/Key.tsx
  packages/slate-editor/src/components/KeyboardKey/KeyboardKey.tsx
  packages/slate-editor/src/components/KeyboardKey/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.module.scss
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
Labels: Type - Feature

#254 [MT-5125] Change - Rich [+] menu tooltip content
  packages/slate-editor/src/components/TooltipV2/Tooltip.module.scss
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/extensions/floating-add-menu/index.ts
  packages/slate-editor/src/extensions/floating-add-menu/types.ts
  packages/slate-editor/src/modules/editor/Editor.stories.tsx
  packages/slate-editor/src/modules/editor/types.ts
Labels: Type - Feature

#241 Dev - ESM-only releases
  babel.cjs.config.json
  babel.config.json
  babel.esm.config.json
  package-lock.json
  packages/slate-commons/gulpfile.js
  packages/slate-commons/package.json
  packages/slate-editor/.storybook/main.cjs
  packages/slate-editor/.storybook/preview.jsx
  packages/slate-editor/gulpfile.js
  packages/slate-editor/jest.config.cjs
  packages/slate-editor/package.json
  packages/slate-editor/src/components/LoadingPlaceholder/LoadingPlaceholder.tsx
  packages/slate-editor/src/components/Menu/index.ts
  packages/slate-editor/src/components/OptionsGroup/Option.tsx
  packages/slate-editor/src/components/Portals/BasePortalV2.tsx
  packages/slate-editor/src/components/Portals/TextSelectionPortalV2.tsx
  packages/slate-editor/src/components/Portals/convertClientRect.ts
  packages/slate-editor/src/extensions/autoformat/transforms/autoformatBlock.ts
  packages/slate-editor/src/extensions/autoformat/transforms/autoformatMark.ts
  packages/slate-editor/src/extensions/autoformat/transforms/autoformatText.ts
  packages/slate-editor/src/extensions/autoformat/utils/getMatchRange.ts
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
  packages/slate-editor/src/extensions/galleries/lib/normalizeInvalidGallery.test.tsx
  packages/slate-editor/src/extensions/galleries/lib/shuffleImages.ts
  packages/slate-editor/src/extensions/galleries/transforms/updateGallery.ts
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/press-contacts/components/FloatingPressContactsMenu.tsx
  packages/slate-editor/src/extensions/story-bookmark/transforms/updateStoryBookmark.ts
  packages/slate-editor/src/extensions/tables/TablesExtension.tsx
  packages/slate-editor/src/extensions/tables/normalization.ts
  packages/slate-editor/src/lib/createDataTransfer.ts
  packages/slate-editor/src/lib/hooks/useUniqueId.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/createEditor.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEqual.ts
  packages/slate-editor/src/modules/editor/test-utils.ts
  packages/slate-editor/src/modules/editor/useOnChange.ts
  packages/slate-editor/src/modules/editor/usePendingOperation.ts
  packages/slate-editor/src/modules/rich-formatting-menu/components/FormattingDropdown.tsx
  packages/slate-editor/src/modules/rich-formatting-menu/lib/getCurrentFormatting.ts
  packages/slate-editor/tsconfig.json
  packages/slate-lists/gulpfile.js
  packages/slate-lists/package.json
  packages/slate-tables/gulpfile.js
  packages/slate-tables/package.json
  packages/slate-types/gulpfile.js
  packages/slate-types/package.json
Labels: Type - Development Experience

#255 Dev - Turborepo builds
  .gitignore
  package-lock.json
  package.json
  packages/slate-commons/gulpfile.js
  packages/slate-commons/package.json
  packages/slate-commons/tsconfig.build.json
  packages/slate-commons/tsconfig.json
  packages/slate-editor/gulpfile.js
  packages/slate-editor/package.json
  packages/slate-editor/tsconfig.build.json
  packages/slate-editor/tsconfig.json
  packages/slate-lists/gulpfile.js
  packages/slate-lists/package.json
  packages/slate-lists/tsconfig.build.json
  packages/slate-lists/tsconfig.json
  packages/slate-tables/gulpfile.js
  packages/slate-tables/package.json
  packages/slate-tables/tsconfig.build.json
  packages/slate-types/gulpfile.js
  packages/slate-types/package.json
  tsconfig.json
  turbo.json
Labels: Type - Development Experience

#259 [MT-5195] Track how [+] menu was triggered
  packages/slate-editor/src/extensions/floating-add-menu/FloatingAddMenuExtension.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Feature

#257 [MT-5180] Fix - UX for copying/cutting/pasting tables
  packages/slate-commons/src/commands/findLeafLocation.ts
  packages/slate-commons/src/commands/findLeafPath.ts
  packages/slate-commons/src/commands/findLeafPoint.ts
  packages/slate-commons/src/commands/findLeafRange.ts
  packages/slate-editor/src/extensions/paste-slate-content/lib/isFragment.ts
  packages/slate-editor/src/extensions/tables/TablesExtension.tsx
  packages/slate-editor/src/extensions/tables/onKeyDown.ts
  packages/slate-editor/src/jsx.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-tables/src/TablesEditor.ts
  packages/slate-tables/src/core/onKeyDown.ts
  packages/slate-tables/src/core/withTablesCopyPasteBehavior.ts
  packages/slate-tables/src/queries/findParentCell.ts
  packages/slate-tables/src/queries/findParentTable.ts
  packages/slate-tables/src/queries/index.ts
Labels: Type - Feature, Type - Fix

#256 [MT-5175] Add normalization to fix broken tables
  package-lock.json
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/allowChildren.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/Tables.test.tsx
  packages/slate-tables/package.json
  packages/slate-tables/src/TablesEditor.ts
  packages/slate-tables/src/normalization/index.ts
  packages/slate-tables/src/normalization/insertMissingCells.ts
  packages/slate-tables/src/normalization/removeEmptyRows.ts
  packages/slate-tables/src/normalization/splitColSpanCells.ts
  packages/slate-tables/src/normalization/splitRowSpanCells.ts
  packages/slate-tables/src/withNormalization.ts
  packages/slate-tables/src/withTables.ts
Labels: Type - Feature

#258 [MT-5197] Fix - Correct checking of edge line in Table cells
  packages/slate-commons/src/commands/findLeafPoint.ts
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/commands/isCursorOnEdgeOfContainer.ts
  packages/slate-tables/src/core/onKeyDown.ts
Labels: Type - Feature

#261 [MT-5203] Make the filtered results appear in a relevant order
  packages/slate-editor/src/extensions/floating-add-menu/lib/useKeyboardFiltering.ts
Labels: Type - Feature

#262 [MT-5127] Focus editor on closing toolbar
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
Labels: Type - Feature

#265 [MT-5199] Feature - Prototype for inserting blocks around
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/extensions/tables/TablesExtension.tsx
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/modules/editor/Editor.module.scss
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/createEditor.ts
  packages/slate-editor/src/modules/editor/index.ts
  packages/slate-editor/src/modules/editor/plugins/index.ts
  packages/slate-editor/src/modules/editor/plugins/withDefaultTextBlock.ts
  packages/slate-editor/src/modules/editor/types.ts
Labels: Type - Feature, Type - Experiment

#270 [MT-5199] Feature - Tracking block insertion via entry points and hotkeys
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/extensions/insert-block-hotkey/InsertBlockHotkeyExtension.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Feature

#271 [MT-5199] Fix - Entry points styling regression
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
Labels: Type - Fix

#272 [MT-5210] Feature - Update layout and functionality of plus menu dropdown
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
Labels: Type - Feature

#274 [MT-5210] Fix - [+] menu position on initial render
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
Labels: Type - Fix

#275 [MT-5210] Fix - [+] menu min-height when filtered
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.tsx
Labels: Type - Fix

#276 [MT-5219] Fix - Editor inserting empty block before cropped image
  packages/slate-commons/src/selection/highest.test.ts
  packages/slate-commons/src/selection/highest.ts
  packages/slate-editor/src/extensions/loader/transforms/replaceLoader.ts
Labels: Type - Fix

#279 [MT-5032] Fix - Editor crashing on pasting Table from a web-page
  .eslintrc.cjs
  packages/slate-editor/src/components/LoadingPlaceholder/LoadingPlaceholder.stories.tsx
  packages/slate-editor/src/extensions/tables/normalization.test.tsx
  packages/slate-editor/src/modules/events/EventsEditor.ts
  packages/slate-editor/src/modules/uploadcare/UploadcareEditor.ts
  packages/slate-tables/src/normalization/insertMissingCells.ts
Labels: Type - Fix
