Repository prezly/slate, pull requests merged in 2022-06, with the labels that each got.

#200 [MT-5004] Fix - Inter-blocks spacing
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/extensions/image/components/ImageElement.module.scss
  packages/slate-editor/src/extensions/image/components/ImageElement.tsx
  packages/slate-editor/src/extensions/paragraphs/components/ParagraphElement.module.scss
  packages/slate-editor/src/extensions/rich-formatting/components/Headings/HeadingElement.module.scss
  packages/slate-editor/src/extensions/rich-formatting/components/Lists/ListElement.module.scss
  packages/slate-editor/src/modules/editor/Editor.module.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Fix

#202 [MT-5017] Fix - Use image original src as a return value from the `useImage` hook
  packages/slate-editor/src/components/LoadingPlaceholder/ImageWithLoadingPlaceholder.tsx
  packages/slate-editor/src/lib/createImageProgressPromise/index.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithProgress.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithReadableStream.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithXmlHttpRequest.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/index.ts
  packages/slate-editor/src/lib/hooks/useImage.ts
  packages/slate-editor/src/lib/index.ts
Labels: Type - Bug, Type - Refactoring

#204 [MT-5029] Fix - Gallery images are not visible in older Safari versions
  package-lock.json
  package.json
  packages/slate-editor/src/components/LoadingPlaceholder/ImageWithLoadingPlaceholder.tsx
  packages/slate-editor/src/extensions/loader/components/LoaderElement.tsx
  packages/slate-editor/src/lib/hooks/useAsyncProgressFn.ts
  packages/slate-editor/src/modules/editor/lib/insertUploadingFile.ts
Labels: Type - Fix

#209 Refactor - Html deserialization configuration & composition
  packages/slate-commons/src/types/DeserializeElement.ts
  packages/slate-commons/src/types/DeserializeHtml.ts
  packages/slate-commons/src/types/DeserializeMarks.ts
  packages/slate-commons/src/types/index.ts
  packages/slate-editor/src/extensions/blockquote/BlockquoteExtension.tsx
  packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx
  packages/slate-editor/src/extensions/default-deserialization/DefaultDeserializationExtension.ts
  packages/slate-editor/src/extensions/default-deserialization/index.ts
  packages/slate-editor/src/extensions/divider/DividerExtension.tsx
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx
  packages/slate-editor/src/extensions/heading/HeadingExtension.tsx
  packages/slate-editor/src/extensions/html/HtmlExtension.tsx
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx
  packages/slate-editor/src/extensions/list/ListExtension.tsx
  packages/slate-editor/src/extensions/mentions/MentionsExtension.ts
  packages/slate-editor/src/extensions/paragraphs/ParagraphsExtension.tsx
  packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx
  packages/slate-editor/src/extensions/story-bookmark/StoryBookmarkExtension.tsx
  packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx
  packages/slate-editor/src/extensions/text-styling/TextStylingExtension.tsx
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/combineElementDeserializerConfig.test.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/combineElementDeserializerConfig.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/combineMarksDeserializersConfig.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createElementsDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createMarksDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createTextDeserializer.ts
  packages/slate-editor/src/modules/html-deserialization/combineExtensionsElementDeserializers.ts
  packages/slate-editor/src/modules/html-deserialization/combineExtensionsMarkDeserializers.ts
  packages/slate-editor/src/modules/html-deserialization/composeElementDeserializer.test.ts
  packages/slate-editor/src/modules/html-deserialization/composeElementDeserializer.ts
  packages/slate-editor/src/modules/html-deserialization/composeMarksDeserializer.test.ts
  packages/slate-editor/src/modules/html-deserialization/composeMarksDeserializer.ts
  packages/slate-editor/src/modules/html-deserialization/index.ts
Labels: Type - Refactoring

#212 [MT-5018] Refactor - Simplify html parsing code
  package-lock.json
  packages/slate-commons/src/index.ts
  packages/slate-commons/src/lib/index.ts
  packages/slate-commons/src/types/DeserializeHtml.ts
  packages/slate-editor/package.json
  packages/slate-editor/src/extensions/default-deserialization/DefaultDeserializationExtension.ts
  packages/slate-editor/src/extensions/default-deserialization/index.ts
  packages/slate-editor/src/extensions/text-styling/TextStylingExtension.tsx
  packages/slate-editor/src/extensions/text-styling/lib/detectMark.ts
  packages/slate-editor/src/extensions/text-styling/lib/isBold.ts
  packages/slate-editor/src/extensions/text-styling/lib/isItalic.ts
  packages/slate-editor/src/extensions/text-styling/lib/isSubscript.ts
  packages/slate-editor/src/extensions/text-styling/lib/isSuperscript.ts
  packages/slate-editor/src/extensions/text-styling/lib/isUnderline.ts
  packages/slate-editor/src/lib/index.ts
  packages/slate-editor/src/lib/isGoogleDocsWrapper.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createElementsDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createMarksDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/createTextDeserializer.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/dom.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/createDeserialize/temporarilyReplaceNode.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/deserializeHtml/__tests__/08.recursive-marks.html
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/deserializeHtml/__tests__/08.recursive-marks.json
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/deserializeHtml/__tests__/09.elements-with-text-styling.html
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/deserializeHtml/__tests__/09.elements-with-text-styling.json
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/deserializeHtml/deserializeHtml.test.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/normalizers/normalizeGoogleDocsAppleNewlines.ts
  packages/slate-editor/src/modules/editor/plugins/withDeserializeHtml/normalizers/normalizeGoogleDocsDividers.ts
Labels: Type - Refactoring

#214 Upgrade - Slate v0.81.0
  package-lock.json
  package.json
  packages/slate-commons/package.json
  packages/slate-editor/package.json
  packages/slate-editor/src/modules/editor/Editor.test.tsx
  packages/slate-editor/src/modules/editor/createEditor.ts
  packages/slate-editor/src/modules/editor/plugins/index.ts
  packages/slate-editor/src/modules/editor/plugins/withRichBlocks.ts
  packages/slate-editor/src/modules/editor/plugins/withVoids.test.tsx
  packages/slate-editor/src/modules/editor/plugins/withVoids.ts
  packages/slate-lists/package.json
  packages/slate-types/package.json
Labels: Type - Refactoring

#211 Refactor root type normalization
  .eslintrc.cjs
  package-lock.json
  package.json
  packages/slate-commons/src/types/Extension.ts
  packages/slate-editor/src/extensions/blockquote/BlockquoteExtension.tsx
  packages/slate-editor/src/extensions/coverage/CoverageExtension.tsx
  packages/slate-editor/src/extensions/divider/DividerExtension.tsx
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/file-attachment/FileAttachmentExtension.tsx
  packages/slate-editor/src/extensions/galleries/GalleriesExtension.tsx
  packages/slate-editor/src/extensions/heading/HeadingExtension.tsx
  packages/slate-editor/src/extensions/html/HtmlExtension.tsx
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/list/ListExtension.tsx
  packages/slate-editor/src/extensions/loader/LoaderExtension.tsx
  packages/slate-editor/src/extensions/paragraphs/ParagraphsExtension.tsx
  packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx
  packages/slate-editor/src/extensions/story-bookmark/StoryBookmarkExtension.tsx
  packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/jsx.ts
  packages/slate-editor/src/modules/editor/createEditor.ts
  packages/slate-editor/src/modules/editor/plugins/index.ts
  packages/slate-editor/src/modules/editor/plugins/withRootElements.ts
  packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
  packages/slate-editor/src/modules/nodes-hierarchy/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/normilizers/rootNodeOnly.ts
  packages/slate-editor/src/modules/nodes-hierarchy/types.ts
  packages/slate-editor/src/modules/nodes-hierarchy/withNodesHierarchy.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/withNodesHierarchy.ts
Labels: Type - Refactoring

#216 [MT-5010] Refactor - Avoid editor HOC wrappers
  packages/slate-editor/src/modules/editor/Editor.stories.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/index.ts
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-editor/src/modules/editor/useOnChange.ts
  packages/slate-editor/src/modules/editor/withAvailableWidth.tsx
  packages/slate-editor/src/modules/editor/withDebounce.tsx
Labels: Type - Refactoring

#219 Fix - List elements `ref` support
  packages/slate-editor/src/extensions/list/components/ListElement.tsx
  packages/slate-editor/src/extensions/list/components/ListItemElement.tsx
  packages/slate-editor/src/extensions/list/components/ListItemTextElement.tsx
Labels: Type - Fix

#217 [MT-5010] Refactor - Convert `Editor` API to unctrolled input
  package-lock.json
  package.json
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/commands/isValidSelection.ts
  packages/slate-commons/src/commands/resetNodes.ts
  packages/slate-editor/package.json
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithProgress.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithReadableStream.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithXmlHttpRequest.ts
  packages/slate-editor/src/lib/hooks/index.ts
  packages/slate-editor/src/lib/hooks/useFunction.ts
  packages/slate-editor/src/modules/editor/Editor.stories.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/index.ts
  packages/slate-editor/src/modules/editor/lib/index.ts
  packages/slate-editor/src/modules/editor/lib/insertUploadingFile.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEqual.ts
  packages/slate-editor/src/modules/editor/lib/isEditorValueEquivalent.ts
  packages/slate-editor/src/modules/editor/types.ts
Labels: Type - Fix

#221 Upgrade - Typescript
  package-lock.json
  package.json
  packages/slate-editor/src/components/Portals/ElementPortalV2.tsx
  packages/slate-editor/src/modules/editable/lib/combineRenderLeaf.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
Labels: Type - Refactoring

#224 [MT-5050] Suggestion - Tables
  package.json
  packages/slate-editor/package.json
  packages/slate-editor/src/extensions/table/TableExtension.tsx
  packages/slate-editor/src/extensions/table/components/elements/TableCellElement.tsx
  packages/slate-editor/src/extensions/table/constants.ts
  packages/slate-editor/src/extensions/table/index.ts
  packages/slate-editor/src/extensions/table/types.ts
  packages/slate-editor/src/extensions/tables/TablesExtension.tsx
  packages/slate-editor/src/extensions/tables/components/TableMenu.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableCellElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableContext.ts
  packages/slate-editor/src/extensions/tables/components/elements/TableElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/TableRowElement.tsx
  packages/slate-editor/src/extensions/tables/components/elements/elements.module.scss
  packages/slate-editor/src/extensions/tables/components/elements/index.ts
  packages/slate-editor/src/extensions/tables/components/index.ts
  packages/slate-editor/src/extensions/tables/index.ts
  packages/slate-editor/src/extensions/tables/lib.ts
  packages/slate-editor/src/extensions/tables/normalization.ts
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/lib/table/insertTable.ts
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-tables/package.json
  packages/slate-tables/src/TableEditor.tsx
  packages/slate-tables/src/TablesEditor.tsx
  packages/slate-tables/src/commands/index.ts
  packages/slate-tables/src/commands/insertColumn.ts
  packages/slate-tables/src/commands/insertRow.ts
  packages/slate-tables/src/commands/insertTable.ts
  packages/slate-tables/src/commands/removeColumn.ts
  packages/slate-tables/src/commands/removeRow.ts
  packages/slate-tables/src/commands/removeTable.ts
  packages/slate-tables/src/core/Matrix/Matrix.ts
  packages/slate-tables/src/core/Matrix/createGridWithSpans.ts
  packages/slate-tables/src/core/Traverse/Traverse.ts
  packages/slate-tables/src/index.ts
  packages/slate-tables/src/nodes/TableCellNode.ts
  packages/slate-tables/src/nodes/TableNode.ts
  packages/slate-tables/src/nodes/TableRowNode.ts
  packages/slate-tables/src/queries/isInTable.ts
  packages/slate-tables/src/withTableEditor.ts
  packages/slate-tables/src/withTables.ts
  packages/slate-tables/tsconfig.json
  packages/slate-types/src/nodes/TableNode.ts
Labels: Type - Refactoring

#227 [MT-5073] Consistent capitals in menu item captions
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Fix
