Repository prezly/slate, pull requests merged in 2022-01, with the labels that each got.

#68 Refactor - Namespace exports
  packages/slate-editor/src/components/ImageSizeWarning/ImageSizeWarning.tsx
  packages/slate-editor/src/components/ImageWithLoadingPlaceholderV2.tsx
  packages/slate-editor/src/components/LoadingPlaceholderV2/Placeholder.tsx
  packages/slate-editor/src/components/LoadingPlaceholderV2/index.ts
  packages/slate-editor/src/components/TooltipV2/Tooltip.tsx
  packages/slate-editor/src/components/TooltipV2/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/index.ts
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/Container.tsx
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/index.ts
  packages/slate-editor/src/modules/editor-v4-components/LinkWithTooltip/LinkWithTooltip.tsx
  packages/slate-editor/src/modules/editor-v4-components/index.ts
  packages/slate-editor/src/modules/editor-v4-coverage/components/CoverageElement/CoverageElement.tsx
  packages/slate-editor/src/modules/editor-v4-coverage/components/FloatingCoverageMenu/FloatingCoverageMenu.tsx
  packages/slate-editor/src/modules/editor-v4-embed/components/FloatingEmbedInput/FloatingEmbedInput.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-loader/components/LoaderElement/LoaderElement.tsx
  packages/slate-editor/src/modules/editor-v4-press-contacts/components/FloatingPressContactsMenu/FloatingPressContactsMenu.tsx
  packages/slate-editor/src/modules/editor-v4-video/components/FloatingVideoInput/FloatingVideoInput.tsx
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/FloatingWebBookmarkInput/FloatingWebBookmarkInput.tsx
  packages/slate-editor/src/modules/editor-v4/index.ts
Labels: Type - Refactoring

#64 [MT-4449] Autoformat
  .gitignore
  package-lock.json
  packages/slate-commons/src/commands/getPrevChars.test.tsx
  packages/slate-commons/src/commands/getPrevChars.ts
  packages/slate-commons/src/commands/index.ts
  packages/slate-commons/src/types/Extension.ts
  packages/slate-commons/src/types/WithOverrides.ts
  packages/slate-editor/package-lock.json
  packages/slate-editor/package.json
  packages/slate-editor/src/modules/editor-v4-autoformat/AutoformatExtension.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/autoformatUtils.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/constants.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/index.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/transforms/autoformatBlock.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/transforms/autoformatMark.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/transforms/autoformatText.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/transforms/index.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/types.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/utils/getMatchPoints.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/utils/getMatchRange.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/utils/index.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/utils/isPreviousCharacterEmpty.ts
  packages/slate-editor/src/modules/editor-v4-autoformat/withAutoformat.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/autoformatRules.ts
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-editor/src/modules/editor-v4/useCreateEditor.ts
Labels: Type - Feature

#72 Refactor - List & Heading components organisation
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/BulletedListElement/BulletedListElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/BulletedListElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/HeadingOneElement/HeadingOneElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/HeadingOneElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/HeadingTwoElement/HeadingTwoElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/HeadingTwoElement/HeadingTwoElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/HeadingTwoElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Headings/HeadingElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Headings/HeadingElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Headings/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemElement/ListItemElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemElement/ListItemElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemTextElement/ListItemTextElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemTextElement/ListItemTextElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/ListItemTextElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/ListElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/ListItemElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/ListItemTextElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/Lists.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/NumberedListElement/NumberedListElement.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/NumberedListElement/NumberedListElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/NumberedListElement/index.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/RichTextElement.tsx
Labels: Type - Refactoring

#71 [MT-4437] Feature - Text alignment
  packages/slate-commons/src/commands/alignment.ts
  packages/slate-commons/src/commands/index.ts
  packages/slate-editor/src/icons/Align-Center.svg
  packages/slate-editor/src/icons/Align-Left.svg
  packages/slate-editor/src/icons/Align-Right.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor-v4-paragraphs/components/ParagraphElement/ParagraphElement.tsx
  packages/slate-editor/src/modules/editor-v4-paragraphs/lib/normalizeRedundantParagraphAttributes.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/BlockQuoteElement/BlockQuoteElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Headings/HeadingElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/ListElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/ListItemTextElement.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/Lists/Lists.scss
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/RichFormattingMenu.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/components/RichFormattingToolbar.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/normalizeRedundantRichTextAttributes.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/types/index.ts
  packages/slate-types/src/index.ts
  packages/slate-types/src/lib/index.ts
  packages/slate-types/src/lib/isAlignableElement.ts
  packages/slate-types/src/nodes/HeadingNode.ts
  packages/slate-types/src/nodes/ListNode.ts
  packages/slate-types/src/nodes/ParagraphNode.ts
  packages/slate-types/src/nodes/QuoteNode.ts
  packages/slate-types/src/nodes/TextNode.ts
  packages/slate-types/src/nodes/index.ts
  packages/slate-types/src/nodes/interfaces/Alignable.ts
  packages/slate-types/src/nodes/interfaces/Stylable.ts
  packages/slate-types/src/nodes/interfaces/index.ts
Labels: Type - Feature

#73 [MT-4575] Fix text formatting toolbar being positioned outside of editable content
  packages/slate-editor/src/components/Portals/TextSelectionPortalV2.tsx
Labels: Type - Fix

#75 [MT-4462] Refactor - Floating add menu module
  packages/slate-editor/src/lib/hooks/react-use.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Input.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Input.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Input/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useEditorSelectionMemory.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useKeyboardFiltering.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useKeyboardNavigation.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useMenu.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useMenuToggle.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/types.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/types/index.ts
Labels: Type - Refactoring

#77 [MT-4594] Feature - New [+] button menu
  packages/slate-editor/src/icons/.editorconfig
  packages/slate-editor/src/icons/Add.svg
  packages/slate-editor/src/icons/Bats-Illustration.svg
  packages/slate-editor/src/icons/Component-Attachment.svg
  packages/slate-editor/src/icons/Component-Contact.svg
  packages/slate-editor/src/icons/Component-Coverage.svg
  packages/slate-editor/src/icons/Component-Divider.svg
  packages/slate-editor/src/icons/Component-Embed.svg
  packages/slate-editor/src/icons/Component-Gallery.svg
  packages/slate-editor/src/icons/Component-H1.svg
  packages/slate-editor/src/icons/Component-H2.svg
  packages/slate-editor/src/icons/Component-Image.svg
  packages/slate-editor/src/icons/Component-Social-Post.svg
  packages/slate-editor/src/icons/Component-Text.svg
  packages/slate-editor/src/icons/Component-Video.svg
  packages/slate-editor/src/icons/Component-Web-Bookmark.svg
  packages/slate-editor/src/icons/Warning-Circle.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/components/Button/Button.scss
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/components/Button/Button.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ClassicDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ClassicDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Dropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/betaLastComparator.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/groupOptions.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/isComponent.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/sortBetaOptionsLast.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useKeyboardFiltering.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/types.ts
  packages/slate-editor/src/modules/editor-v4-rich-formatting/index.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/menuOptions.tsx
  packages/slate-editor/src/styles/shared.scss
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Feature

#79 [MT-4583] Tweak "Play" button overlay colors
  packages/slate-editor/src/icons/PlayButton.svg
  packages/slate-editor/src/modules/editor-v4-video/components/VideoElement/VideoElement.scss
Labels: Type - Fix

#80 [MT-4592] Tweak provider name font-size in vertical bookmark block
  packages/slate-editor/src/modules/editor-v4-web-bookmark/components/WebBookmarkElement/WebBookmarkElement.scss
Labels: Type - Fix

#78 [MT-4595] Feature - New [+] button menu positioning
  package-lock.json
  packages/slate-editor/package.json
  packages/slate-editor/src/@types/popper-max-size-modifier.d.ts
  packages/slate-editor/src/components/Portals/BasePortal.scss
  packages/slate-editor/src/components/Portals/BasePortal.tsx
  packages/slate-editor/src/components/Portals/BasePortalV2.scss
  packages/slate-editor/src/components/Portals/BasePortalV2.tsx
  packages/slate-editor/src/components/Portals/ElementPortal.tsx
  packages/slate-editor/src/components/Portals/ElementPortalV2.tsx
  packages/slate-editor/src/components/Portals/getUpdatedPosition.ts
  packages/slate-editor/src/components/Portals/index.ts
  packages/slate-editor/src/components/Portals/types.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/Container.tsx
  packages/slate-editor/src/modules/editor-v4-components/FloatingContainer/useCurrentDomNode.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/Input.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.scss
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/components/ModernDropdown.tsx
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/styles/mixins.scss
Labels: Type - Feature

#82 [MT-4597] Fix - New [+] button text blocks focus
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-rich-formatting/lib/toggleBlock.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/autoformatRules.ts
Labels: Type - Fix

#85 [MT-4624] Add Quote option to the new [+] menu
  packages/slate-editor/src/icons/Component-Quote.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/menuOptions.tsx
Labels: Type - Feature

#84 [MT-4596] Feature - New [+] menu hotkey
  packages/slate-editor/src/lib/hooks/react-use.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenu.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/FloatingAddMenuExtension.tsx
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/index.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/isMenuHotkey.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/shouldShowMenuButton.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useKeyboardFiltering.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useKeyboardNavigation.ts
  packages/slate-editor/src/modules/editor-v4-floating-add-menu/lib/useMenuToggle.ts
  packages/slate-editor/src/modules/editor-v4/EditorV4.tsx
  packages/slate-editor/src/modules/editor-v4/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor-v4/test-utils.ts
  packages/slate-editor/src/modules/editor-v4/types/index.ts
Labels: Type - Feature
