Repository prezly/slate, pull requests merged in 2023-05, with the labels that each got.

#408 Dev - Simplify & Improve GitHub actions
  .github/workflows/build.yml
  .github/workflows/dependencies.yml
  .github/workflows/prettier.yml
  .github/workflows/storybook.yml
  .github/workflows/test.yml
  package.json
  packages/slate-editor/storybook/.npmrc
Labels: Type - Development Experience

#413 [CARE-1603] Fix toolbar menu missing spacing
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Fix

#415 [CARE-1627] Fix - Unignore storybook stories path for resolution
  .github/workflows/storybook.yml
  packages/slate-editor/gulpfile.js
Labels: Type - Fix

#416 [CARE-1580] Refactor - Replace react-bootstrap's `Dropdown` with headlessui's `Listbox` in `Menu.Dropdown`
  packages/slate-editor/package.json
  packages/slate-editor/src/components/Menu/Dropdown.module.scss
  packages/slate-editor/src/components/Menu/Dropdown.tsx
  packages/slate-editor/src/components/Menu/Menu.module.scss
  packages/slate-editor/src/components/Menu/Menu.stories.tsx
  packages/slate-editor/src/styles/helpers.scss
Labels: Type - Feature, Type - Refactoring

#417 [DEV-10754] Allow triggering search via events, minor text changes
  packages/slate-editor/src/components/SearchInput/SearchInput.tsx
  packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
  packages/slate-editor/src/modules/events/EventsEditor.ts
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Feature

#418 [DEV-10804] Implement menu with options for PressContactElement
  packages/slate-editor/src/extensions/press-contacts/components/PressContactElement.module.scss
  packages/slate-editor/src/extensions/press-contacts/components/PressContactElement.tsx
  packages/slate-editor/src/extensions/press-contacts/components/PressContactMenu.tsx
  packages/slate-editor/src/extensions/press-contacts/components/index.ts
  packages/slate-editor/src/extensions/press-contacts/lib/createContactNode.ts
  packages/slate-editor/src/extensions/press-contacts/lib/index.ts
  packages/slate-editor/src/extensions/press-contacts/lib/normalizations.ts
  packages/slate-editor/src/extensions/press-contacts/lib/updatePressContact.ts
  packages/slate-editor/src/icons/ContactLayoutCard.svg
  packages/slate-editor/src/icons/ContactLayoutSignature.svg
  packages/slate-editor/src/icons/Envelope.svg
  packages/slate-editor/src/icons/Globe.svg
  packages/slate-editor/src/icons/Mobile.svg
  packages/slate-editor/src/icons/Phone.svg
  packages/slate-editor/src/icons/Social-Facebook.svg
  packages/slate-editor/src/icons/Social-Twitter.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/Contact.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/Contact.test.tsx.snap
  packages/slate-types/src/nodes/ContactNode.ts
Labels: Type - Feature

#419 Fix - Compare options first before comparing references in contacts
  packages/slate-editor/src/extensions/press-contacts/PressContactsExtension.tsx
Labels: Type - Fix
