Repository prezly/slate, pull requests merged in 2023-09, with the labels that each got.

#490 [DEV-11525] Implement `Embed` ⇆ `WebBookmark` presentations transform
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx
  packages/slate-editor/src/extensions/embed/transforms/convertEmbed.ts
  packages/slate-editor/src/extensions/embed/transforms/index.ts
  packages/slate-editor/src/extensions/embed/types.ts
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
  packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
  packages/slate-editor/src/extensions/video/transforms/convertVideo.ts
  packages/slate-editor/src/extensions/video/transforms/index.ts
  packages/slate-editor/src/extensions/video/types.ts
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkElement.tsx
  packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkMenu.tsx
  packages/slate-editor/src/extensions/web-bookmark/lib/createWebBookmark.ts
  packages/slate-editor/src/extensions/web-bookmark/lib/normalizations.ts
  packages/slate-editor/src/extensions/web-bookmark/lib/parseSerializedElement.ts
  packages/slate-editor/src/extensions/web-bookmark/transforms/convertWebBookmark.ts
  packages/slate-editor/src/extensions/web-bookmark/transforms/index.ts
  packages/slate-editor/src/extensions/web-bookmark/transforms/removeWebBookmark.ts
  packages/slate-editor/src/extensions/web-bookmark/transforms/updateWebBookmark.ts
  packages/slate-editor/src/extensions/web-bookmark/types.ts
  packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/Bookmark.test.tsx
  packages/slate-types/src/nodes/BookmarkNode.ts
Labels: Type - Feature, Type - Refactoring

#493 [DEV-11549] Fix - "Change to" menu is visible even with feature flag disabled
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/placeholders/index.ts
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/index.ts
  packages/slate-editor/src/extensions/web-bookmark/types.ts
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/types.ts
Labels: Priority - High, Type - Fix

#495 [DEV-11536] Disable embed sizing controls for certain providers
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx
Labels: Type - Feature

#497 [DEV-11519] Feature - Autolink URLs in the pasted content
  packages/slate-editor/src/extensions/inline-links/InlineLinksExtension.tsx
  packages/slate-editor/src/extensions/inline-links/behaviour/index.ts
  packages/slate-editor/src/extensions/inline-links/behaviour/withPastedContentAutolinking.ts
  packages/slate-editor/src/extensions/inline-links/behaviour/withSelectionAutolinking.ts
  packages/slate-editor/src/extensions/inline-links/lib/autolinkPlaintext.test.ts
  packages/slate-editor/src/extensions/inline-links/lib/autolinkPlaintext.ts
  packages/slate-editor/src/extensions/inline-links/lib/createLink.ts
  packages/slate-editor/src/extensions/inline-links/lib/index.ts
  packages/slate-editor/src/extensions/inline-links/lib/isUrl.ts
  packages/slate-editor/src/lib/index.ts
  packages/slate-editor/src/lib/urls.ts
Labels: Type - Feature

#498 [DEV-11547] Feature - Implement switching Bookmark/Embed/Video to/from InlineLink
  packages/slate-commons/src/commands/getNodePath.ts
  packages/slate-commons/src/commands/replaceNode.tsx
  packages/slate-editor/src/components/Toolbox/Section.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx
  packages/slate-editor/src/extensions/embed/transforms/convertEmbed.ts
  packages/slate-editor/src/extensions/embed/types.ts
  packages/slate-editor/src/extensions/image/ImageExtension.tsx
  packages/slate-editor/src/extensions/inline-links/index.ts
  packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
  packages/slate-editor/src/extensions/video/transforms/convertVideo.ts
  packages/slate-editor/src/extensions/video/types.ts
  packages/slate-editor/src/extensions/web-bookmark/WebBookmarkExtension.tsx
  packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkMenu.tsx
  packages/slate-editor/src/extensions/web-bookmark/lib/index.ts
  packages/slate-editor/src/extensions/web-bookmark/lib/normalizations.ts
  packages/slate-editor/src/extensions/web-bookmark/normalizations/fixUuidCollisions.ts
  packages/slate-editor/src/extensions/web-bookmark/normalizations/index.ts
  packages/slate-editor/src/extensions/web-bookmark/normalizations/normalizeUrlAttribute.ts
  packages/slate-editor/src/extensions/web-bookmark/normalizations/unsetUnknownAttributes.ts
  packages/slate-editor/src/extensions/web-bookmark/transforms/convertWebBookmark.ts
  packages/slate-editor/src/extensions/web-bookmark/types.ts
  packages/slate-editor/src/lib/humanFriendlyUrl.ts
  packages/slate-editor/src/lib/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-editor/src/modules/rich-formatting-menu/LinkMenu.tsx
  packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx
  packages/slate-editor/src/modules/rich-formatting-menu/lib/convertLink.ts
  packages/slate-editor/src/modules/rich-formatting-menu/lib/index.ts
  packages/slate-editor/src/modules/rich-formatting-menu/types.ts
Labels: Type - Feature

#499 [DEV-11526] Feature - Auto-convert pasted URLs to embeds
  packages/slate-editor/src/extensions/inline-links/behaviour/withPastedContentAutolinking.ts
  packages/slate-editor/src/extensions/inline-links/behaviour/withSelectionAutolinking.ts
  packages/slate-editor/src/extensions/inline-links/lib/index.ts
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
  packages/slate-editor/src/extensions/placeholders/PlaceholdersManager.ts
  packages/slate-editor/src/extensions/placeholders/behaviour/index.ts
  packages/slate-editor/src/extensions/placeholders/behaviour/withPastedUrlsUnfurling.ts
  packages/slate-editor/src/extensions/placeholders/elements/AttachmentPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/GalleryPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/ImagePlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/MediaPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/lib/handleOembed.ts
  packages/slate-editor/src/extensions/placeholders/lib/replacePlaceholder.ts
  packages/slate-editor/src/lib/index.ts
  packages/slate-editor/src/lib/isUrl.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-editor/src/modules/rich-formatting-menu/lib/convertLink.ts
Labels: Type - Feature

#502 [CARE-3062] Fix editor not seeing modifications Video node `layout` prop
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
Labels: Type - Fix
