Repository prezly/slate, pull requests merged in 2023-07, with the labels that each got.

#448 [CARE-1797] Feature - Story Bookmark/Embed placeholder
  packages/slate-editor/package.json
  packages/slate-editor/src/components/SearchInput/SearchInput.tsx
  packages/slate-editor/src/components/SearchInput/types.ts
  packages/slate-editor/src/extensions/floating-add-menu/components/Dropdown.module.scss
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
  packages/slate-editor/src/extensions/placeholders/PlaceholdersManager.ts
  packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholder.tsx
  packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.stories.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.stories.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/index.ts
  packages/slate-editor/src/extensions/placeholders/normalization/removeDisabledPlaceholders.ts
  packages/slate-editor/src/extensions/story-bookmark/index.ts
  packages/slate-editor/src/extensions/story-bookmark/lib/index.ts
  packages/slate-editor/src/extensions/story-bookmark/lib/useFloatingStoryBookmarkInput.ts
  packages/slate-editor/src/extensions/story-bookmark/types.ts
  packages/slate-editor/src/extensions/story-embed/index.ts
  packages/slate-editor/src/extensions/story-embed/lib/index.ts
  packages/slate-editor/src/extensions/story-embed/lib/useFloatingStoryEmbedInput.ts
  packages/slate-editor/src/extensions/story-embed/types.ts
  packages/slate-editor/src/icons/Placeholder-Story.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.module.scss
  packages/slate-editor/src/modules/components/FloatingStoryEmbedInput/FloatingStoryEmbedInput.tsx
  packages/slate-editor/src/modules/components/FloatingStoryEmbedInput/index.ts
  packages/slate-editor/src/modules/components/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/lib/images/createImageReplaceHandler.ts
  packages/slate-editor/src/modules/editor/menuOptions.tsx
  packages/slate-editor/src/modules/editor/test-utils.ts
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Feature

#449 [CARE-1797] Cleanup editor events
  packages/slate-editor/src/extensions/placeholders/elements/ContactPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/CoveragePlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryBookmarkPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/StoryEmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/WebBookmarkPlaceholderElement.tsx
  packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkElement/StoryBookmarkElement.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Refactoring

#450 [CARE-2017] Forbid translating editor area
  packages/slate-editor/src/modules/editable/EditableWithExtensions.tsx
Labels: Type - Fix

#451 Refactor - Remove `canvas` dependency
  package.json
Labels: Type - Refactoring

#452 [CARE-2019] Fix placeholders not reactivatable after blurring
  packages/slate-editor/src/extensions/placeholders/PlaceholdersManager.ts
Labels: Type - Fix

#453 [CARE-1932] Enable SelectionDecoration only when linking text
  packages/slate-commons/src/types/DecorateFactory.ts
  packages/slate-editor/src/extensions/decorate-selection/DecorateSelectionExtension.tsx
  packages/slate-editor/src/extensions/decorate-selection/components/SelectionHighlight.module.scss
  packages/slate-editor/src/extensions/decorate-selection/constants.ts
  packages/slate-editor/src/extensions/decorate-selection/decorateSelection.ts
  packages/slate-editor/src/extensions/decorate-selection/index.ts
  packages/slate-editor/src/modules/decorations/DecorationsContext.ts
  packages/slate-editor/src/modules/decorations/DecorationsProvider.tsx
  packages/slate-editor/src/modules/decorations/index.ts
  packages/slate-editor/src/modules/decorations/useDecoration.ts
  packages/slate-editor/src/modules/decorations/useDecorationFactory.ts
  packages/slate-editor/src/modules/editable/lib/createExtensionsDecorators.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/rich-formatting-menu/RichFormattingMenu.tsx
Labels: Type - Fix

#454 [CARE-1965] Fix - Infinite list structure normalization loop
  package.json
  packages/slate-editor/src/modules/editor/Editor.test.tsx
  packages/slate-editor/src/modules/editor/__tests__/expected/list-normalization-4.json
  packages/slate-editor/src/modules/editor/__tests__/input/list-normalization-4.json
  packages/slate-editor/src/modules/editor/test-utils.ts
  packages/slate-lists/src/lib/index.ts
  packages/slate-lists/src/lib/isContainingTextNodes.ts
  packages/slate-lists/src/lib/isElementOrEditor.ts
  packages/slate-lists/src/normalizations/normalizeListChildren.ts
  packages/slate-lists/src/normalizations/normalizeListItemChildren.ts
  packages/slate-lists/src/normalizations/normalizeOrphanListItem.ts
  packages/slate-lists/src/normalizations/normalizeOrphanListItemText.ts
  packages/slate-lists/src/normalizations/normalizeSiblingLists.ts
Labels: Type - Fix
