Repository prezly/slate, pull requests merged in 2023-08, with the labels that each got.

#455 [CARE-2142] Fix editor block outline position regression
  packages/slate-editor/src/components/EditorBlock/EditorBlock.module.scss
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
Labels: Type - Fix

#456 [DEV-11237] Implement CTA button support in editor
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.module.scss
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.tsx
  packages/slate-editor/src/components/SearchInput/SearchInput.tsx
  packages/slate-editor/src/extensions/button-block/ButtonBlockExtension.tsx
  packages/slate-editor/src/extensions/button-block/ButtonBlockNode.ts
  packages/slate-editor/src/extensions/button-block/components/Button/Button.module.scss
  packages/slate-editor/src/extensions/button-block/components/Button/Button.tsx
  packages/slate-editor/src/extensions/button-block/components/Button/index.ts
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.module.scss
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.tsx
  packages/slate-editor/src/extensions/button-block/components/index.ts
  packages/slate-editor/src/extensions/button-block/index.ts
  packages/slate-editor/src/extensions/button-block/lib/createButtonBlock.ts
  packages/slate-editor/src/extensions/button-block/lib/fixDuplicateButtonBlockUuid.ts
  packages/slate-editor/src/extensions/button-block/lib/index.ts
  packages/slate-editor/src/extensions/button-block/lib/insertButtonBlock.ts
  packages/slate-editor/src/extensions/button-block/lib/normalizeRedundantButtonBlockAttributes.ts
  packages/slate-editor/src/extensions/button-block/lib/parseSerializedButtonBlockElement.ts
  packages/slate-editor/src/extensions/button-block/transforms/index.ts
  packages/slate-editor/src/extensions/button-block/transforms/removeButtonBlock.ts
  packages/slate-editor/src/extensions/button-block/transforms/updateButtonBlock.ts
  packages/slate-editor/src/icons/ButtonLayoutCenter.svg
  packages/slate-editor/src/icons/ButtonLayoutLeft.svg
  packages/slate-editor/src/icons/ButtonLayoutRight.svg
  packages/slate-editor/src/icons/ButtonLayoutWide.svg
  packages/slate-editor/src/icons/Component-Button.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.stories.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/getEnabledExtensions.ts
  packages/slate-editor/src/modules/editor/menuOptions.tsx
  packages/slate-editor/src/modules/editor/test-utils.ts
  packages/slate-editor/src/modules/editor/types.ts
  packages/slate-editor/src/modules/events/types.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
  packages/slate-editor/src/styles/variables.scss
Labels: Type - Feature, Priority - High

#457 [DEV-11281] Implement "accordion" UI element for the overlay menu
  packages/slate-editor/src/components/Accordion/Accordion.module.scss
  packages/slate-editor/src/components/Accordion/Accordion.stories.tsx
  packages/slate-editor/src/components/Accordion/Accordion.tsx
  packages/slate-editor/src/components/Accordion/index.ts
  packages/slate-editor/src/components/index.ts
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.tsx
  packages/slate-editor/src/icons/Caret.svg
  packages/slate-editor/src/icons/index.ts
Labels: Type - Feature

#460 [DEV-11322] Warn users if CTA is unsupported in their current theme
  packages/slate-editor/src/components/InfoText/InfoText.tsx
  packages/slate-editor/src/extensions/button-block/ButtonBlockExtension.tsx
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.module.scss
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.tsx
Labels: Type - Feature

#459 [DEV-11280] Position overlay menu below the button element
  packages/slate-editor/src/components/EditorBlock/EditorBlock.tsx
  packages/slate-editor/src/components/EditorBlock/getMenuPopperModifiers.ts
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx
  packages/slate-editor/src/modules/popper-options-context/types.ts
Labels: Type - Feature

#463 [DEV-11401] Tweak CTA button menu item description
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Fix

#465 [DEV-11397] Fix long button text wrapping
  packages/slate-editor/src/extensions/button-block/components/Button/Button.module.scss
Labels: Type - Fix

#464 [DEV-11282] Inherit prev block alignment for new buttons
  packages/slate-editor/src/extensions/button-block/lib/insertButtonBlock.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
Labels: Type - Feature

#466 [DEV-7586] Feature - Implement UI for video block settings
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
  packages/slate-editor/src/extensions/video/components/VideoMenu.module.scss
  packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
  packages/slate-editor/src/extensions/video/index.ts
  packages/slate-editor/src/extensions/video/lib/createVideoBookmark.ts
  packages/slate-editor/src/extensions/video/lib/normalizeRedundantVideoAttributes.ts
  packages/slate-editor/src/extensions/video/lib/parseSerializedElement.ts
  packages/slate-editor/src/extensions/video/transforms/index.ts
  packages/slate-editor/src/extensions/video/transforms/removeVideo.ts
  packages/slate-editor/src/extensions/video/transforms/updateVideo.ts
  packages/slate-editor/src/extensions/video/types.ts
  packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/Video.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/Video.test.tsx.snap
  packages/slate-types/src/nodes/VideoNode.ts
Labels: Type - Feature

#467 [DEV-11412] Feature - Warn if video size options are not supported by the theme
  packages/slate-editor/src/components/InfoText/InfoText.module.scss
  packages/slate-editor/src/components/InfoText/InfoText.tsx
  packages/slate-editor/src/extensions/button-block/ButtonBlockExtension.tsx
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockElement.tsx
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.module.scss
  packages/slate-editor/src/extensions/button-block/components/ButtonBlockMenu.tsx
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
  packages/slate-editor/src/extensions/video/components/VideoMenu.module.scss
  packages/slate-editor/src/extensions/video/components/VideoMenu.tsx
Labels: Type - Feature

#468 [DEV-7586] Fix VideoNode layout modification detection
  packages/slate-editor/src/extensions/video/VideoExtension.tsx
Labels: Type - Fix

#470 [DEV-11473] Feature - Update data model to support EmbedNode `layout`
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/embed/EmbedNode.ts
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/embed/index.ts
  packages/slate-editor/src/extensions/embed/lib/createEmbed.ts
  packages/slate-editor/src/extensions/embed/lib/normalizeRedundantEmbedAttributes.ts
  packages/slate-editor/src/extensions/embed/lib/parseSerializedElement.ts
  packages/slate-editor/src/extensions/embed/transforms/removeEmbed.ts
  packages/slate-editor/src/extensions/embed/types.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/hyperscript.ts
  packages/slate-editor/src/modules/nodes-hierarchy/hierarchySchema.ts
  packages/slate-editor/src/modules/nodes-hierarchy/queries/isAllowedOnTopLevel.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/Embed.test.tsx.snap
  packages/slate-types/src/nodes/EmbedNode.ts
  packages/slate-types/src/nodes/index.ts
Labels: Type - Feature

#471 [DEV-11492] Enhance YouTube placeholder component and its menu item
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#472 [DEV-11486] Fix Embed screenshot skewed aspect ratio in EmailEditor
  packages/slate-editor/src/components/LoadingPlaceholder/ImageWithLoadingPlaceholder.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithProgress.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithReadableStream.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/fetchImageWithXmlHttpRequest.ts
  packages/slate-editor/src/lib/fetchImageWithProgress/index.ts
  packages/slate-editor/src/lib/hooks/useImage.ts
  packages/slate-editor/src/lib/index.ts
Labels: Type - Fix

#473 [DEV-11490] Enhance Instagram Placeholders and Menu Item
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#474 [DEV-11491] Feature - Implement "Placeholders" and dedicated "Menu Item" for Dropbox
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-Dropbox.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#475 [DEV-11495] Feature - Implement "Placeholders" and dedicated "Menu Item" for X (Twitter)
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-X.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#476 [DEV-11496][DEV-11497][DEV-11498] Implement dedicated Placeholders and Menu Item for Vimeo, Soundcloud and Giphy
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-Giphy.svg
  packages/slate-editor/src/icons/Component-SoundCloud.svg
  packages/slate-editor/src/icons/Component-Vimeo.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#477 [DEV-11515][DEV-11499][DEV-11500][DEV-11516] Implement dedicated Placeholders and Menu Items for TikTok, Spotify and Facebook
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-Facebook.svg
  packages/slate-editor/src/icons/Component-Giphy.svg
  packages/slate-editor/src/icons/Component-Spotify.svg
  packages/slate-editor/src/icons/Component-TikTok.svg
  packages/slate-editor/src/icons/Component-Vimeo.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature, Type - Fix

#478 [DEV-11501][DEV-11504][DEV-11503] Implement dedicated Placeholders and Menu Items for Google Maps, Google Sheets and Google Docs
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-GoogleDocs.svg
  packages/slate-editor/src/icons/Component-GoogleMaps.svg
  packages/slate-editor/src/icons/Component-GoogleSheets.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#481 [DEV-11474] Feature - EmbedNode menu & layout controls
  packages/slate-editor/src/components/OptionsGroup/OptionsGroup.module.scss
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedMenu.module.scss
  packages/slate-editor/src/extensions/embed/components/EmbedMenu.tsx
  packages/slate-editor/src/extensions/embed/index.ts
  packages/slate-editor/src/extensions/embed/lib/index.ts
  packages/slate-editor/src/extensions/embed/normalizations/fixUuidCollisions.ts
  packages/slate-editor/src/extensions/embed/normalizations/index.ts
  packages/slate-editor/src/extensions/embed/normalizations/normalizeRedundantEmbedAttributes.ts
  packages/slate-editor/src/extensions/embed/transforms/index.ts
  packages/slate-editor/src/extensions/embed/transforms/removeEmbed.ts
  packages/slate-editor/src/extensions/embed/transforms/updateEmbed.ts
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
Labels: Type - Feature

#479 [DEV-11505][DEV-11506][DEV-11507][DEV-11444] Implement dedicated Placeholders and Menu Items for Calendly, Eventbrite and Typeform | Improve image keyword aliases
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-Calendly.svg
  packages/slate-editor/src/icons/Component-Eventbrite.svg
  packages/slate-editor/src/icons/Component-Typeform.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#480 [DEV-11502][DEV-11517] Implement generic Audio & Podcast options with dedicated placeholders
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-Audio.svg
  packages/slate-editor/src/icons/Component-Podcast.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#482 [DEV-11474] Fix Embed node comparator to take into account new `layout` property
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
Labels: Type - Fix

#483 [DEV-11508][DEV-11510][DEV-11509] Implement dedicated Placeholders and Menu Items for Pinterest, Tally and Microsoft Teams
  packages/slate-editor/src/extensions/placeholders/PlaceholderNode.ts
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/icons/Component-MicrosoftTeams.svg
  packages/slate-editor/src/icons/Component-Pinterest.svg
  packages/slate-editor/src/icons/Component-Tally.svg
  packages/slate-editor/src/icons/index.ts
  packages/slate-editor/src/modules/editor/Editor.tsx
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#484 [DEV-11512] Feature - Rearrange new provider-specific embed options
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Fix

#485 [DEV-11511] Improve YouTube search keywords
  packages/slate-editor/src/modules/editor/menuOptions.tsx
Labels: Type - Feature

#486 [DEV-7592] Feature - Reroute embeds to video or web bookmark, if it serves better
  packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
  packages/slate-editor/src/extensions/placeholders/elements/EmbedPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/SocialPostPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
  packages/slate-editor/src/extensions/placeholders/lib/handleOembed.ts
  packages/slate-editor/src/extensions/placeholders/lib/index.ts
Labels: Type - Feature

#487 [DEV-11546] Add oEmbed-rerouting to Video placeholders too
  packages/slate-editor/src/extensions/placeholders/PlaceholdersExtension.tsx
  packages/slate-editor/src/extensions/placeholders/elements/VideoPlaceholderElement.tsx
Labels: Type - Fix

#489 [DEV-11518] Feature - Render Tally embeds as web bookmarks in emails
  packages/slate-editor/src/extensions/embed/EmbedExtension.tsx
  packages/slate-editor/src/extensions/embed/components/EmbedElement.tsx
  packages/slate-editor/src/extensions/story-bookmark/components/StoryBookmarkElement/StoryBookmarkBlock.tsx
  packages/slate-editor/src/extensions/web-bookmark/components/WebBookmarkElement.tsx
  packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.stories.tsx
  packages/slate-editor/src/modules/components/BookmarkCard/BookmarkCard.tsx
  packages/slate-editor/src/modules/components/BookmarkCard/Container.tsx
  packages/slate-editor/src/modules/components/BookmarkCard/index.ts
  packages/slate-editor/src/modules/components/index.ts
  packages/slate-editor/src/modules/editor/test-utils.ts
Labels: Type - Feature, Type - Refactoring
