Repository prezly/slate, pull requests merged in 2024-01, with the labels that each got.

#513 [DEV-7347] Fix Icomoon dependency
  packages/slate-editor/src/components/ImageSizeWarning/ImageSizeWarning.tsx
  packages/slate-editor/src/icons/WarningTriangle.svg
Labels: Type - Fix

#514 [CARE-3721] Upgrade - Slate dependencies
  .eslintrc.cjs
  package.json
  packages/slate-commons/package.json
  packages/slate-editor/package.json
  packages/slate-editor/src/extensions/placeholders/components/InputPlaceholder.tsx
  packages/slate-editor/src/extensions/placeholders/components/Placeholder.tsx
  packages/slate-editor/src/extensions/placeholders/components/SearchInputPlaceholder.tsx
  packages/slate-lists/package.json
  packages/slate-tables/package.json
  packages/slate-types/package.json
  sync-package-versions.mjs
Labels: Type - Dependency Upgrade

#516 [CARE-3632] Add missing tracking to converting video block
  packages/slate-editor/src/extensions/video/components/VideoElement.tsx
  packages/slate-editor/src/modules/events/types.ts
Labels: Type - Fix

#523 [DEV-12401] Add `header_footer` support in StoryEmbedNode
  packages/slate-editor/src/extensions/story-embed/StoryEmbedExtension.tsx
  packages/slate-editor/src/extensions/story-embed/lib/createStoryEmbed.ts
  packages/slate-editor/src/extensions/story-embed/lib/normalizeRedundantStoryEmbedAttributes.ts
  packages/slate-editor/src/extensions/story-embed/transforms/updateStoryEmbed.ts
  packages/slate-editor/src/modules/nodes-hierarchy/tests/StoryEmbed.test.tsx
  packages/slate-editor/src/modules/nodes-hierarchy/tests/__snapshots__/StoryEmbed.test.tsx.snap
  packages/slate-types/package.json
  packages/slate-types/src/nodes/StoryEmbedNode.ts
Labels: Type - Feature

#525 [CARE-4306] Update outdated dependencies with security issues
  lerna.json
  package.json
  packages/slate-editor/package.json
  packages/slate-editor/tsconfig.json
Labels: Type - Dependency Upgrade

#526 Update Storybook dependencies
  packages/slate-editor/storybook/package.json
  packages/slate-editor/storybook/pnpm-lock.yaml
Labels: Type - Dependency Upgrade
